# Generated by Django 5.0.3 on 2024-09-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_sumorder_alter_category_options_alter_menu_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sumorder',
            name='created_at',
        ),
        migrations.AddField(
            model_name='sumorder',
            name='created_at_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sumorder',
            name='created_at_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
